/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.*;
import java.awt.event.ComponentEvent;

/**
 *
 * @author ASUS
 */
public class HomePageFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomePageFrm
     */
    public HomePageFrm() {
        initComponents();
//        setSize(1000, 700);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        lbSanPham = new javax.swing.JLabel();
        lbNCC = new javax.swing.JLabel();
        lbNhapHang = new javax.swing.JLabel();
        lbPhieuNhap = new javax.swing.JLabel();
        lbXuatHang = new javax.swing.JLabel();
        lbPhieuXuat = new javax.swing.JLabel();
        lbTonKho = new javax.swing.JLabel();
        lbTK = new javax.swing.JLabel();
        lbThongKe = new javax.swing.JLabel();
        lbDoiThongTin = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(255, 153, 153));
        jPanel11.setForeground(new java.awt.Color(255, 153, 153));

        lbSanPham.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_product_25px_2.png"))); // NOI18N
        lbSanPham.setText("SẢN PHẨM");
        lbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSanPhamMouseClicked(evt);
            }
        });

        lbNCC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_supplier_25px.png"))); // NOI18N
        lbNCC.setText("NHÀ CUNG CẤP");
        lbNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNCCMouseClicked(evt);
            }
        });

        lbNhapHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_import_25px.png"))); // NOI18N
        lbNhapHang.setText("NHẬP HÀNG");
        lbNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhapHangMouseClicked(evt);
            }
        });

        lbPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_file_25px_2.png"))); // NOI18N
        lbPhieuNhap.setText("PHIẾU NHẬP");
        lbPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieuNhapMouseClicked(evt);
            }
        });

        lbXuatHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbXuatHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXuatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_export_25px.png"))); // NOI18N
        lbXuatHang.setText("XUẤT HÀNG");
        lbXuatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXuatHangMouseClicked(evt);
            }
        });

        lbPhieuXuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPhieuXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPhieuXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_database_daily_export_25px.png"))); // NOI18N
        lbPhieuXuat.setText("PHIẾU XUẤT");
        lbPhieuXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieuXuatMouseClicked(evt);
            }
        });

        lbTonKho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTonKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTonKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-warehouse-25.png"))); // NOI18N
        lbTonKho.setText("TỒN KHO");
        lbTonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTonKhoMouseClicked(evt);
            }
        });

        lbTK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_test_account_25px.png"))); // NOI18N
        lbTK.setText("TÀI KHOẢN");
        lbTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTKMouseClicked(evt);
            }
        });

        lbThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/statisticals.png"))); // NOI18N
        lbThongKe.setText("THỐNG KÊ");
        lbThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThongKeMouseClicked(evt);
            }
        });

        lbDoiThongTin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDoiThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDoiThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-information-25.png"))); // NOI18N
        lbDoiThongTin.setText("ĐỔI THÔNG TIN");
        lbDoiThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDoiThongTinMouseClicked(evt);
            }
        });

        lbDangXuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_25px.png"))); // NOI18N
        lbDangXuat.setText("ĐĂNG XUẤT");
        lbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbXuatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieuXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbDoiThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
            .addComponent(lbDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lbSanPham)
                .addGap(18, 18, 18)
                .addComponent(lbNCC)
                .addGap(18, 18, 18)
                .addComponent(lbNhapHang)
                .addGap(18, 18, 18)
                .addComponent(lbPhieuNhap)
                .addGap(18, 18, 18)
                .addComponent(lbXuatHang)
                .addGap(18, 18, 18)
                .addComponent(lbPhieuXuat)
                .addGap(18, 18, 18)
                .addComponent(lbTonKho)
                .addGap(18, 18, 18)
                .addComponent(lbTK)
                .addGap(18, 18, 18)
                .addComponent(lbThongKe)
                .addGap(18, 18, 18)
                .addComponent(lbDoiThongTin)
                .addGap(18, 18, 18)
                .addComponent(lbDangXuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainContent.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                mainContentComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void lbNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNCCMouseClicked
        // TODO add your handling code here:
        NhaCungCap nhaCungCap = new NhaCungCap();
        this.mainContent.setLayout(new BorderLayout());
        this.mainContent.removeAll();
        this.mainContent.add(nhaCungCap, BorderLayout.CENTER);
        nhaCungCap.setVisible(true);
        this.mainContent.revalidate();
        this.mainContent.repaint();
//        nhaCungCap.setSize(mainContent.getWidth(), mainContent.getHeight());
//        mainContent.addComponentListener(new java.awt.event.ComponentAdapter() {
//            public void componentResized(java.awt.event.ComponentEvent evt) {
//                nhaCungCap.setSize(mainContent.getWidth(), mainContent.getHeight());
//            }
//        });

    }//GEN-LAST:event_lbNCCMouseClicked

    private void lbNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhapHangMouseClicked
        NhapHang nhapHang = new NhapHang();
        this.mainContent.removeAll();
        this.mainContent.add(nhapHang).setVisible(true);
    }//GEN-LAST:event_lbNhapHangMouseClicked

    private void lbPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieuNhapMouseClicked
        NhapHang phieuNhap = new NhapHang();
        this.mainContent.removeAll();
        this.mainContent.add(phieuNhap).setVisible(true);
    }//GEN-LAST:event_lbPhieuNhapMouseClicked

    private void lbXuatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXuatHangMouseClicked
        // TODO add your handling code here:
        XuatHangForm xuatHangForm = new XuatHangForm();
        this.mainContent.removeAll();
        this.mainContent.add(xuatHangForm).setVisible(true);
    }//GEN-LAST:event_lbXuatHangMouseClicked

    private void lbPhieuXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieuXuatMouseClicked
        // TODO add your handling code here:
        XuatHangForm phieuXuatForm = new XuatHangForm();
        this.mainContent.removeAll();
        this.mainContent.add(phieuXuatForm).setVisible(true);
    }//GEN-LAST:event_lbPhieuXuatMouseClicked

    private void lbTonKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTonKhoMouseClicked
        // TODO add your handling code here:
        TonKho tonKho = new TonKho();
        this.mainContent.removeAll();
        this.mainContent.add(tonKho).setVisible(true);
    }//GEN-LAST:event_lbTonKhoMouseClicked

    private void lbTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTKMouseClicked
        // TODO add your handling code here:
        AccountFrm accountFrm = new AccountFrm();
        this.mainContent.removeAll();
        this.mainContent.add(accountFrm).setVisible(true);
    }//GEN-LAST:event_lbTKMouseClicked

    private void lbThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThongKeMouseClicked
        // TODO add your handling code here:
        ThongKeForm thongKeForm = new ThongKeForm();
        this.mainContent.removeAll();
        this.mainContent.add(thongKeForm).setVisible(true);
    }//GEN-LAST:event_lbThongKeMouseClicked

    private void lbDoiThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDoiThongTinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbDoiThongTinMouseClicked

    private void lbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbDangXuatMouseClicked

    private void lbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSanPhamMouseClicked
        // TODO add your handling code here:
        SanPhamFrm sanPhamFrm = new SanPhamFrm();
        this.mainContent.setLayout(new BorderLayout());
        this.mainContent.removeAll();
        this.mainContent.add(sanPhamFrm, BorderLayout.CENTER);
        sanPhamFrm.setVisible(true);
        this.mainContent.revalidate();
        this.mainContent.repaint();
    }//GEN-LAST:event_lbSanPhamMouseClicked

    private void mainContentComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_mainContentComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mainContentComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel11;
    private javax.swing.JLabel lbDangXuat;
    private javax.swing.JLabel lbDoiThongTin;
    private javax.swing.JLabel lbNCC;
    private javax.swing.JLabel lbNhapHang;
    private javax.swing.JLabel lbPhieuNhap;
    private javax.swing.JLabel lbPhieuXuat;
    private javax.swing.JLabel lbSanPham;
    private javax.swing.JLabel lbTK;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JLabel lbTonKho;
    private javax.swing.JLabel lbXuatHang;
    private javax.swing.JPanel mainContent;
    // End of variables declaration//GEN-END:variables
}
